/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.bju.cps450.analysis;

import com.bju.cps450.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTString(TString node);
    void caseTBool(TBool node);
    void caseTBegin(TBegin node);
    void caseTClass(TClass node);
    void caseTElse(TElse node);
    void caseTEnd(TEnd node);
    void caseTFrom(TFrom node);
    void caseTIf(TIf node);
    void caseTInherits(TInherits node);
    void caseTInt(TInt node);
    void caseTIs(TIs node);
    void caseTLoop(TLoop node);
    void caseTMe(TMe node);
    void caseTNew(TNew node);
    void caseTNull(TNull node);
    void caseTWhile(TWhile node);
    void caseTThen(TThen node);
    void caseTTrue(TTrue node);
    void caseTFalse(TFalse node);
    void caseTAnd(TAnd node);
    void caseTOr(TOr node);
    void caseTNot(TNot node);
    void caseTTab(TTab node);
    void caseTDot(TDot node);
    void caseTAssignOp(TAssignOp node);
    void caseTLParen(TLParen node);
    void caseTRParen(TRParen node);
    void caseTLBracket(TLBracket node);
    void caseTRBracket(TRBracket node);
    void caseTComma(TComma node);
    void caseTSemiColon(TSemiColon node);
    void caseTColon(TColon node);
    void caseTPeriod(TPeriod node);
    void caseTConcat(TConcat node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTEqual(TEqual node);
    void caseTId(TId node);
    void caseTComment(TComment node);
    void caseTIdentifier(TIdentifier node);
    void caseTIntLiteral(TIntLiteral node);
    void caseTStrLit(TStrLit node);
    void caseTIllegalStrLit(TIllegalStrLit node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
